# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://jupytext.readthedocs.io/en/latest/using-pre-commit.html for
#   jupytext pre-commit instructions and examples
repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.2
    hooks:
      -   id: reorder-python-imports
          application-directories: .:src
  - repo: local
    hooks:
      - id: format-ipynb
        name: format-ipynb
        entry: jupytext --from ipynb --pipe black --check flake8 --pre-commit
        pass_filenames: false
        language: python
      - id: jupytext
        name: jupytext
        entry: jupytext --from ipynb --to py:light --pre-commit
        pass_filenames: false
        language: python
