channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  # For binaries needed to draw causal graphs
  - graphviz=2.42.3
  # For binaries needed to enable no-hassle, CI friendly latex compilation
  - tectonic=0.3.3
  # Ensure the environment uses its own pip.
  - pip
  # Ensure that pip-tools is installed somehow
  - pip-tools=5.4.0
  # Above, list any packages that MUST be installed via conda
  - pip:
    # Install all pip-installable packages
    # - -r file:requirements.txt
