channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.7
  - pip
  # Above, list any packages that MUST be installed via conda
  - pip:
    # Install all pip-installable packages
    - -r file:requirements.txt
