# Run the entire project workflow
name: Project Workflow

# Run this workflow every time a new commit is pushed or a pull-request is
# merged to your repository's master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  project-workflow:
    # Name the Job
    name: Execute the project workflow
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    # Set the python versions to use
    strategy:
      matrix:
        python: [3.7, 3.8]

    steps:
      # Step 1: Check out a copy of your repository on the ubuntu-latest machine
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Make sure conda is installed, with mamba for speed
      - name: Setup Python with Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }}
          mamba-version: "*"
          channels: conda-forge,anaconda,defaults
          channel-priority: true
          activate-environment: causal2020
          environment-file: environment.yml
          auto-activate-base: false

      # Step 3: Make sure the project is installed locally & can commit if needed
      - name: Install package locally
        shell: bash -l {0}
        run: |
          pip-compile requirements.in
          pip install -r requirements.txt
          flit install --pth-file
          pre-commit install

      # Step 4: Run the project's workflow
      - name: Run project workflow
        shell: bash -l {0}
        run: |
          make imagedir
          python article/compile_article.py
